name: Node.js CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
        working-directory: client
      - run: npm run deploy
        working-directory: client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
