name: Node.js CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
        working-directory: client
      - run: npm run build
        working-directory: client
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build
